file(READ ${LIBATRAC9_DIR}/unpack.c libatrac9Unpack)
set(libatrac9OldGuard "block->GradientEndUnit < 0 || block->GradientEndUnit >= 48")
set(libatrac9NewGuard "block->GradientEndUnit < 0 || block->GradientEndUnit > 31")
string(FIND "${libatrac9Unpack}" "${libatrac9OldGuard}" libatrac9GuardPosition)
if(libatrac9GuardPosition EQUAL -1)
    message(FATAL_ERROR "LibAtrac9 gradient guard has changed; review the local bounds fix")
endif()
string(REPLACE "${libatrac9OldGuard}" "${libatrac9NewGuard}" libatrac9Unpack "${libatrac9Unpack}")
file(MAKE_DIRECTORY ${LIBATRAC9_PATCHED_DIR})
file(WRITE ${LIBATRAC9_PATCHED_DIR}/unpack.c "${libatrac9Unpack}")
