set(LIBUSB_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(LIBUSB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(LIBUSB_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LIBUSB_INSTALL_TARGETS OFF CACHE BOOL "" FORCE)
set(LIBUSB_ENABLE_UDEV OFF CACHE BOOL "" FORCE)
add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/libusb ${CMAKE_CURRENT_BINARY_DIR}/libusb EXCLUDE_FROM_ALL)
set_target_properties(usb-1.0 PROPERTIES POSITION_INDEPENDENT_CODE ON)

add_library(libSceUsbd SHARED EXCLUDE_FROM_ALL Export.cpp)
target_include_directories(libSceUsbd PRIVATE ${LIBS_INCLUDE_DIR})
target_link_libraries(libSceUsbd PRIVATE usb-1.0)
if(MINGW OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_link_options(libSceUsbd PRIVATE LINKER:--exclude-libs,ALL)
endif()
configure_windows_unwind(libSceUsbd)

if(BUILD_TESTING)
    add_test_executable(guest_usbd_tests ${LIBS_INCLUDE_DIR}/tests/GuestUsbd.cpp)
    target_include_directories(guest_usbd_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_include_directories(guest_usbd_tests SYSTEM PRIVATE $<TARGET_PROPERTY:usb-1.0,INTERFACE_INCLUDE_DIRECTORIES>)
    target_link_libraries(guest_usbd_tests PRIVATE libSceUsbd libc)
    configure_windows_unwind(guest_usbd_tests)
    add_test(NAME guest_usbd COMMAND guest_usbd_tests)
    add_test_executable(guest_usbd_control_tests ${LIBS_INCLUDE_DIR}/tests/GuestUsbdControl.cpp Export.cpp)
    target_include_directories(guest_usbd_control_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_usbd_control_tests PRIVATE usb-1.0 libc)
    target_link_options(guest_usbd_control_tests PRIVATE LINKER:--wrap=libusb_control_transfer)
    configure_windows_unwind(guest_usbd_control_tests)
    add_test(NAME guest_usbd_control COMMAND guest_usbd_control_tests)
    add_test_executable(guest_usbd_async_tests ${LIBS_INCLUDE_DIR}/tests/GuestUsbdAsync.cpp Export.cpp)
    target_include_directories(guest_usbd_async_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_usbd_async_tests PRIVATE usb-1.0 libc)
    foreach(function IN ITEMS alloc_transfer free_transfer submit_transfer cancel_transfer handle_events_timeout)
        target_link_options(guest_usbd_async_tests PRIVATE "LINKER:--wrap=libusb_${function}")
    endforeach()
    configure_windows_unwind(guest_usbd_async_tests)
    add_test(NAME guest_usbd_async COMMAND guest_usbd_async_tests)
    if(WIN32)
        set_tests_properties(guest_usbd PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceUsbd>")
        set_tests_properties(guest_usbd_async PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libc>")
        set_tests_properties(guest_usbd_control PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libc>")
    endif()
endif()
