include(${CMAKE_CURRENT_SOURCE_DIR}/Ngs2Library.cmake)
add_sce_ngs2_library(libSceNgs2.native)

if(MINGW)
    foreach(runtimeLinkFlag IN ITEMS -static-libgcc -static-libstdc++ -static)
        string(REPLACE "${runtimeLinkFlag}" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
    endforeach()
endif()

if(BUILD_TESTING)
    foreach(ngs2Library IN ITEMS libSceNgs2.native libSceNgs2)
        set(testPrefix ngs2)
        if(ngs2Library STREQUAL "libSceNgs2")
            set(testPrefix ngs2_core)
        endif()
        foreach(ngs2Test IN ITEMS Render Atrac9)
            string(TOLOWER ${ngs2Test} testName)
            set(testTarget ${testPrefix}_${testName}_tests)
            add_test_executable(${testTarget} ${CMAKE_CURRENT_SOURCE_DIR}/tests/Ngs2${ngs2Test}.cpp)
            target_include_directories(${testTarget} PRIVATE ${LIBS_INCLUDE_DIR} ${CMAKE_SOURCE_DIR}/3rdparty/LibAtrac9/C/src)
            target_link_libraries(${testTarget} PRIVATE ${ngs2Library} atrac9 libkernel libc)
            configure_windows_unwind(${testTarget})
            add_test(NAME ${testPrefix}_${testName} COMMAND ${testTarget})
            if(WIN32)
                set_tests_properties(${testPrefix}_${testName} PROPERTIES ENVIRONMENT_MODIFICATION
                    "PATH=path_list_prepend:$<TARGET_FILE_DIR:${ngs2Library}>")
            endif()
        endforeach()
    endforeach()
endif()
